#Robocode window sizes
#Wed Sep 09 16:35:26 GMT-03:00 2026
net.sf.robocode.ui.dialog.NewBattleDialog=290,37,842,651
net.sf.robocode.ui.dialog.PreferencesDialog=297,179,794,346
net.sf.robocode.ui.dialog.RobocodeFrame=0,0,927,701
