#Robocode window sizes
#Mon Aug 31 00:58:34 GMT-03:00 2026
net.sf.robocode.ui.dialog.NewBattleDialog=455,144,842,651
net.sf.robocode.ui.dialog.PreferencesDialog=558,367,794,346
net.sf.robocode.ui.dialog.RobocodeFrame=0,0,927,701
